INSERT INTO `produk` (`no_kategori`, `nama`, `deskripsi`, `harga`, `foto`, `slug`) VALUES
(2, 'Apel', 'Dijual perkilogram.', '27000', 'Apel.png', 'apel'),
(2, 'Pisang', 'Dijual persisir.', '7000', 'Pisang.png', 'pisang'),
(2, 'Pepaya', 'Dijual perkilogram.', '5000', 'Pepaya.png', 'pepaya'),
(2, 'Jeruk', 'Dijual perkilogram.', '17000', 'Jeruk.png', 'jeruk'),
(2, 'Melon', 'Dijual perkilogram.', '10000', 'Melon.png', 'melon'),
(2, 'Nanas', 'Dijual perkilogram.', '7000', 'Nanas.png', 'nanas'),
(2, 'Semangka', 'Dijual perkilogram.', '6000', 'Semangka.png', 'semangka'),
(2, 'Lemon', 'Dijual perkilogram.', '10000', 'Lemon.png', 'lemon'),
(1, 'Seledri', 'Dijual perkilogram.', '10000', 'Seledri.png', 'seledri'),
(1, 'Brokoli', 'Dijual perkilogram.', '11000', 'Brokoli.png', 'brokoli'),
(1, 'Kentang', 'Dijual perkilogram.', '11000', 'Kentang.png', 'kentang'),
(1, 'Bawang Putih', 'Dijual perkilogram.', '10000', 'Bawang-Putih.png', 'bawang-putih'),
(1, 'Bawang Merah', 'Dijual perkilogram.', '23000', 'Bawang-Merah.png', 'bawang-merah'),
(1, 'Bawang Daun', 'Dijual perkilogram.', '13000', 'Bawang-Daun.png', 'bawang-daun'),
(1, 'Wortel', 'Dijual perkilogram.', '25000', 'Wortel.png', 'wortel'),
(1, 'Tomat', 'Dijual perkilogram.', '2000', 'Tomat.png', 'tomat'),
(1, 'Terong', 'Dijual perkilogram.', '8000', 'Terong.png', 'terong'),
(1, 'Jamur', 'Dijual perkilogram.', '15000', 'Jamur.png', 'jamur'),
(1, 'Cabai', 'Dijual perkilogram.', '10000', 'Cabai.png', 'cabai'),
(1, 'Lobak', 'Dijual perkilogram.', '12000', 'Lobak.png', 'lobak'),
(1, 'Paprika', 'Dijual perkilogram.', '12000', 'Paprika.png', 'paprika'),
(1, 'Selada', 'Dijual perkilogram.', '7000', 'Selada.png', 'selada');